name: .NET Core CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run tests
      uses: actions/cryptic-wizard/run-specflow-tests@v1.3.3
      with:
        test-assembly-path: SpecflowSelenium/bin/Release/net6.0
        test-assembly-dll: SpecflowSelenium.dll
        output-html: MyTestResults.html

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: MyTestResults.html
